In [16]:
from google.colab import files
uploaded=files.upload()


import pandas as pd
df=pd.read_csv(list(uploaded.keys())[0],encoding='latin-1')
df=df[['v1','v2']]
df.columns=['label','message']
df.head()

Saving spam.csv to spam (1).csv

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [17]:
import os
os.listdir()

['.config', 'sample_data', 'spam.csv', 'spam (1).csv']

In [18]:
import pandas as pd
df=pd.read_csv("spam.csv",encoding='latin-1')
df=df[['v1','v2']]
df.columns=['label','message']
df.head()

  label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [19]:
df['label']=df['label'].map({'ham':0,'spam':1})
df.head()

   label                                            message
0      0  Go until jurong point, crazy.. Available only ...
1      0                      Ok lar... Joking wif u oni...
2      1  Free entry in 2 a wkly comp to win FA Cup fina...
3      0  U dun say so early hor... U c already then say...
4      0  Nah I don't think he goes to usf, he lives aro...

In [20]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [21]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
import re
ps=PorterStemmer()
def transform_text(text):
  text=text.lower()
  text=re.sub('[^a-zA-Z]','',text)
  text=text.split()
  text=[ps.stem(word) for word in text if word not in stopwords.words('english')]
  return "".join(text)
df['transformed']=df['message'].apply(transform_text)
df.head()

,label,message,transformed
0,0,"Go until jurong point, crazy.. Available only ...",gountiljurongpointcrazyavailableonlyinbugisngr...
1,0,Ok lar... Joking wif u oni...,oklarjokingwifuoni
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,freeentryinawklycomptowinfacupfinaltktsstmayte...
3,0,U dun say so early hor... U c already then say...,udunsaysoearlyhorucalreadythensay
4,0,"Nah I don't think he goes to usf, he lives aro...",nahidontthinkhegoestousfhelivesaroundherethough

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(max_features=3000)
X=tfidf.fit_transform(df['transformed']).toarray()
y=df['label'].values

In [24]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=2
)

In [25]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(X_train,y_train)

MultinomialNB()

In [27]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
y_pred=model.predict(X_test)
print("Accuracy:",accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

Accuracy: 0.8609865470852018
[[957   0]
 [155   3]]
              precision    recall  f1-score   support

           0       0.86      1.00      0.93       957
           1       1.00      0.02      0.04       158

    accuracy                           0.86      1115
   macro avg       0.93      0.51      0.48      1115
weighted avg       0.88      0.86      0.80      1115

In [43]:
!git config --global user.name "Purvasi19"
!git config --global user.email "puja190805@gmail.com"
!git clone "https://github.com/Purvasi19/spam_detection.git"
!mv/content/spam_detection/spam.csv /content/spam_detection
%cd /content/spam_detection
!git add spam.ipynb
!git commit -m "first commit"
!git pull origin main --rebase
!git push origin main

Cloning into 'spam_detection'...
fatal: could not read Username for 'https://github.com': No such device or address
/bin/bash: line 1: mv/content/spam_detection/spam.csv: No such file or directory
[Errno 2] No such file or directory: '/content/spam_detection'
/content
fatal: pathspec 'spam.ipynb' did not match any files
On branch main

Initial commit

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.config/
	sample_data/
	spam (1).csv
	spam.csv

nothing added to commit but untracked files present (use "git add" to track)
fatal: Updating an unborn branch with changes added to the index.
error: src refspec main does not match any
error: failed to push some refs to 'origin'